<a href="https://colab.research.google.com/github/Mandira124/Machine-Learning-Beginner-Projects/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment Number: 1

Student Name: Mandira Sharma

Course : COMP 488 Neural Networks And Deep Learning

Roll no:

Date: April 5,2026

Dataset Used: Synthetic data is used

#**Objective**



*   To understand what tensors are and how they are used
*   To perform basic operations like reshaping and broadcasting
*   To compare NumPy and PyTorch results
*   To learn matrix multiplication and eigenvalues
*   To observe numerical precision issues in computation







#**Theoretical Background**

A tensor is a way to store data in multiple dimensions. It can be a single number (scalar), a list (vector), or a table (matrix). In machine learning, all data is stored as tensors.

Reshaping is used to change the structure of data without changing its values. This is important when preparing input for models.

Broadcasting allows operations between tensors of different shapes by automatically expanding them. This helps avoid loops and makes computation faster.

Matrix multiplication is a key operation in machine learning. It is used in neural networks to combine inputs with weights.

Formula for matrix multiplication:

C = A × B

Each element is calculated by multiplying rows and columns.

Eigenvalues represent important directions in data. They are used in techniques like PCA (Principal Component Analysis).

Entropy is a measure of uncertainty in probability. Higher entropy means more randomness.

#**Dataset Description**

= This assignment does not use a real dataset.
Instead, small manually created arrays (tensors) are used to demonstrate operations.

#**IMPLEMENTATION**

Tensor Creation, Reshaping, Broadcasting

In [1]:
import numpy as np
import torch

print("Tensor Creation")

# NumPy tensor
np_tensor = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy Tensor:\n", np_tensor)

# PyTorch tensor
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("PyTorch Tensor:\n", torch_tensor)


print("Reshaping")

x = np.arange(6)
reshaped = x.reshape(2, 3)
print("Original:", x)
print("Reshaped:\n", reshaped)


print("Broadcasting")

a = np.array([[1, 2, 3]])
b = np.array([[1], [2], [3]])

broadcast_result = a + b
print("Broadcasting Result:\n", broadcast_result)

Tensor Creation
NumPy Tensor:
 [[1 2 3]
 [4 5 6]]
PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaping
Original: [0 1 2 3 4 5]
Reshaped:
 [[0 1 2]
 [3 4 5]]
Broadcasting
Broadcasting Result:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


Matrix Multiplication & Eigenvalues

In [2]:
print("Matrix Multiplication\n")

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np_result = np.dot(A, B)
print("NumPy Multiplication:\n", np_result)


print("Eigenvalues")

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix Multiplication

NumPy Multiplication:
 [[19 22]
 [43 50]]
Eigenvalues
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Matrix Multiplication (Manual vs NumPy vs PyTorch)

In [3]:
print("Manual Matrix Multiplication")

# Manual multiplication
manual_result = [
    [A[0][0]*B[0][0] + A[0][1]*B[1][0],
     A[0][0]*B[0][1] + A[0][1]*B[1][1]],

    [A[1][0]*B[0][0] + A[1][1]*B[1][0],
     A[1][0]*B[0][1] + A[1][1]*B[1][1]]
]

print("Manual Result:\n", manual_result)


print("PyTorch Multiplication")

A_t = torch.tensor(A, dtype=torch.float32)
B_t = torch.tensor(B, dtype=torch.float32)

torch_result = torch.matmul(A_t, B_t)
print("PyTorch Result:\n", torch_result)

Manual Matrix Multiplication
Manual Result:
 [[np.int64(19), np.int64(22)], [np.int64(43), np.int64(50)]]
PyTorch Multiplication
PyTorch Result:
 tensor([[19., 22.],
        [43., 50.]])


Numerical Instability / Precision Experiment

In [4]:
print(" Numerical Instability ")

a = 1e10
b = 1e-10

result = (a + b) - a

print("Expected:", b)
print("Actual:", result)

 Numerical Instability 
Expected: 1e-10
Actual: 0.0


#**Experiments**

1) Compared matrix multiplication
using:

   a) Manual calculation

   b) NumPy

   c) PyTorch

2) Observed broadcasting behavior with different shapes

3) Tested numerical instability using very large and very small numbers

(No hyperparameters since no model is used)




#**Results**

1) NumPy and PyTorch gave the same results for matrix multiplication

2) Broadcasting worked correctly and expanded tensors automatically

3) Eigenvalues were successfully computed

4) Numerical instability experiment showed incorrect result (0 instead of small value)

#**Analysis & Discussion**

The tensor operations worked as expected. Broadcasting made operations easier and faster without using loops.

Matrix multiplication is clearly an important operation and is used in machine learning models.

NumPy and PyTorch gave the same results, but PyTorch is more useful for deep learning because it supports GPU.

The numerical instability experiment showed that computers cannot always handle very small and very large numbers together. This can affect machine learning models, especially during training.

Since no model was used, concepts like overfitting or bias-variance were not observed here.




#**Conclusion**

1) Tensors are the basic building blocks of machine learning

2) Reshaping and broadcasting help in handling data efficiently

3) Matrix multiplication is the core operation in neural networks

4) NumPy and PyTorch provide similar results for computations

5) Numerical precision errors can affect results in real applications

6) Understanding these basics is important before building ML models